constraint_physics_inc = include_directories('src')

constraint_physics_lib = static_library('ConstraintPhysics',
    'src/CFM.cpp',
    'src/CollisionDetect.cpp',
    'src/ConstraintSolver.cpp',
    'src/ConvexPrimitive.cpp',
    'src/Geometry.cpp',
    'src/HACD.cpp',
    'src/HolonomicBlockSolver.cpp',
    'src/Octree.cpp',
    'src/PersistentConstraint.cpp',
    'src/PhysicsEngine.cpp',
    'src/RigidBody.cpp',
    include_directories : constraint_physics_inc
)